
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:  
  name: labkube-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: labkube-cluster-admin
  namespace: kube-system
- kind: ServiceAccount
  name: labkube-cluster-admin1
  namespace: kube-system