---
- hosts: kubectrl
  become: true
  tasks:
    - name: get token
      command: kubeadm token create --print-join-command
      register: tokenout
    - copy:
        content: "{{ tokenout.stdout }}"
        dest: "/tmp/token_cmd.sh"
    - debug:
        var: tokenout.stdout
    - name: fetch token_cmd.sh from remote to local
      fetch:
        src: /tmp/token_cmd.sh
        dest: /var/lib/jenkins/fetched/
        flat: yes


- hosts: localhost
  gather_facts: no
  become: true
  connection: local
  tasks:
    - name: update join command file
      aws_s3:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        aws_security_token: "{{ lookup('env', 'AWS_SESSION_TOKEN') }}"
        ec2_region: "eu-west-3"
        bucket: "{{ lookup('env', 'ANSIBLE_BUCKET_NAME') }}"
        mode: put
        object: /token_cmd.sh
        src: /var/lib/jenkins/fetched/token_cmd.sh
