---
- hosts: kubectrl
  become: true
  tasks:
    - name: test kubectl from controlplane
      command: kubectl get nodes
      register: kubectl_output
    - debug: 
        var: kubectl_output.stdout_lines