---
- hosts: kubectrl
  become: yes
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/cleyaws_rsa
  roles:
    - role: '/var/lib/jenkins/workspace/aws_ec2_K8s/ansible_infra/ansible_role/kubecontrolplane'
